[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[redirects]]
  from = "/admin/catalogo"
  to = "/admin/catalogo.html"
  status = 301

[[redirects]]
  from = "/admin/dashboard"
  to = "/admin/dashboard.html"
  status = 301

[[redirects]]
  from = "/admin/suscriptores"
  to = "/admin/suscriptores.html"
  status = 301

[[redirects]]
  from = "/admin/pedidos"
  to = "/admin/pedidos.html"
  status = 301

[[redirects]]
  from = "/portal/dashboard"
  to = "/portal/dashboard.html"
  status = 301

[[redirects]]
  from = "/portal/catalogo"
  to = "/portal/catalogo.html"
  status = 301

[[redirects]]
  from = "/portal/pedido"
  to = "/portal/pedido.html"
  status = 301

[[redirects]]
  from = "/portal/mis-pedidos"
  to = "/portal/mis-pedidos.html"
  status = 301

[[redirects]]
  from = "/portal/cuenta"
  to = "/portal/cuenta.html"
  status = 301
